name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install WordPress
        run: |
          # Install any necessary dependencies (e.g., PHP, MySQL)
          # Download and extract the WordPress files
          wget -O wordpress.tar.gz https://wordpress.org/latest.tar.gz
          tar -xzf wordpress.tar.gz

      - name: Create target directory on EC2
        run: ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@15.206.167.125 "mkdir -p /var/www/html"

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: 15.206.167.125
          REMOTE_USER: ubuntu
          TARGET: /var/www/html


